
solve1 : ../program1.cpp
	g++ ../program1.cpp -o solve1

solve2 : ../program2.cpp
	g++ ../program2.cpp -o solve2

constructor : ../constructor.cpp
	g++ ../constructor.cpp -o constructor

comparator : comparator.cpp
	g++ comparator.cpp -o comparator

showresult : showresult.cpp
	g++ showresult.cpp -o showresult
